### ISSUE TITLE
Graceful error handling issue

### ISSUE THREAD

**Issue by anku94** [pull-stream/pull-stream#110]
Hi,

I have an application using libp2p + pull-streams.

One of the pulls looks like this:

```javascript
pull(
    conn,
    pull.map((v) => {
        return v.toString();
    }),
    collect((err, data) => {
    })
)
```

This works fine. But I'm doing some error testing on my application, which involves shutting down peers randomly mid-communication. Sometimes I get an unhandled exception from inside pull-streams. Here is the stack trace.

```

TypeError: read is not a function
    at C:\Users\t-anj\source\repos\vishrambh-stores\node_modules\pull-stream\throughs\map.js:11:7
    at next (C:\Users\t-anj\source\repos\vishrambh-stores\node_modules\pull-stream\sinks\drain.js:16:11)
    at sink (C:\Users\t-anj\source\repos\vishrambh-stores\node_modules\pull-stream\sinks\drain.js:37:9)
    at pull (C:\Users\t-anj\source\repos\vishrambh-stores\node_modules\pull-stream\pull.js:41:14)
    at node.dialProtocol (C:\Users\t-anj\source\repos\vishrambh-stores\protocolHandler.js:126:7)
    at switch.dial (C:\Users\t-anj\source\repos\vishrambh-stores\node_modules\libp2p\src\index.js:258:27)
    at attemptDial (C:\Users\t-anj\source\repos\vishrambh-stores\node_modules\libp2p-switch\src\dial.js:33:20)
    at nextTransport (C:\Users\t-anj\source\repos\vishrambh-stores\node_modules\libp2p-switch\src\dial.js:102:20)
    at swarm.transport.dial (C:\Users\t-anj\source\repos\vishrambh-stores\node_modules\libp2p-switch\src\dial.js:115:20)
    at dialer.dialMany (C:\Users\t-anj\source\repos\vishrambh-stores\node_modules\libp2p-switch\src\transport.js:49:18)
```

The best I can tell, this is an issue with the `map.js` not handling a failure case correctly, right? Or am I supposed to catch this error somehow?

I'm using the `3.6.2` version.

_Edit_: I realize that I haven't been clear about how exactly to replicate this. I thought that since this is an unhandled error, it should not appear in any case. If more debug information is needed please let me know and I'll add additional debug code in my application to get it.

**Comment by harrysarson** [comment]
It looks to me like `conn` is not a function, could you show us where you get `conn` from?

**Comment by anku94** [comment]
I'm sorry @harrysarson - I was not indeed handling the error from the parent function properly, and it was the malformed `conn` object that was causing this issue. My bad.
