### ISSUE TITLE
TypeError: read is not a function

### ISSUE THREAD

**Issue by christianbundy** [pull-stream/pull-stream#113]
Hello!

I'm learning `pull-stream` and thought the benchmarks might be fun to run, but I'm getting an error when running `benchmarks/pull.js`. Am I doing something wrong here, or could this be a bug?

```console
$ node benchmarks/node.js 
pull3*100000: 2496.285ms
43.60696
$ node benchmarks/pull.js 
/home/christianbundy/Source/pull-stream/pull.js:46
	read(null, function next (err, data) {
	^

TypeError: read is not a function
    at sink (/home/christianbundy/Source/pull-stream/pull.js:46:2)
    at Object.<anonymous> (/home/christianbundy/Source/pull-stream/pull.js:54:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/christianbundy/Source/pull-stream/index.js:7:28)
```

Thanks for your work on this project!

**Comment by dominictarr** [comment]
on master, commit 568e376c8776c2aed748946cc093baf4953dee02 I do not get this error.
I ran them on both node 8 and 10

**Comment by christianbundy** [comment]
Yep, I was on 6ae0c63 (3.6.8), but it looks like it's working great on the most recent commit (3.6.9). Closing, thanks!

```console
$ node benchmarks/node.js
pull3*100000: 2102.561ms
44.67248
```
